package es.zed.pokedb.abstracts;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import es.zed.common.AbstractEvent;
import es.zed.common.AbstractEventBody;
import es.zed.pokedb.AbilityCreatedEvent;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 * Class that describes the pokemon of the events generated by the PokeApi micro-service.
 *
 * @param <B> the event body type.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type_id")
@JsonSubTypes({
    @JsonSubTypes.Type(value = AbilityCreatedEvent.class, name = AbilityCreatedEvent.TYPE_ID),
})
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public abstract class AbstractAbilityEvent<B extends AbstractEventBody> extends AbstractEvent<B> {

  /**
   * Constant value for the context field, unique for users micro-service context.
   */
  public static final String CONTEXT = "POKEDB";

  /**
   * Abstract poke event.
   *
   * @param typeId typeId.
   * @param version version.
   */
  public AbstractAbilityEvent(final String typeId, final String version) {
    super(CONTEXT, typeId);
    setVersion(version);
  }

  /**
   * Abstract poke event.
   *
   * @param origin origin.
   * @param context context.
   * @param typeId typeId.
   * @param messageId messageId.
   * @param version version.
   * @param creationTs creationTs.
   * @param pokemonId pokemonId.
   * @param body body.
   */
  public AbstractAbilityEvent(String origin, String context, String typeId,
      String messageId, String version, Long creationTs, String pokemonId, B body) {
    super(origin, context, typeId, messageId, version, creationTs, pokemonId, body);
  }
}
